### ISSUE TITLE
java.lang.VerifyError: class org.cactoos.list.Mapped overrides final method toString.

### ISSUE THREAD

**Issue by rocket-3** [Vatavuk/verano-http#59]
The code is:

```
public class AppTest {

    @Test
    public void httpPost() {
        final Response response = new Response(
            new ApiUrl().asString(),
            new Post(
                "/api/auth/login",
                new JsonBody(
                    Json.createObjectBuilder().add(
                        "username",
                        "***"
                    ).add(
                        "password",
                        "***"
                    ).build()
                )
            )
        );
        System.out.println(new Body.Of(response).asString());
    }

}
```

The result is: 

```
java.lang.VerifyError: class org.cactoos.list.Mapped overrides final method toString.()Ljava/lang/String;

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at hr.com.vgv.verano.http.HashDict.<init>(HashDict.java:59)
	at hr.com.vgv.verano.http.HashDict.<init>(HashDict.java:51)
	at hr.com.vgv.verano.http.DictInput$Envelope.<init>(DictInput.java:67)
	at hr.com.vgv.verano.http.parts.RequestUri.<init>(RequestUri.java:47)
	at hr.com.vgv.verano.http.wire.apache.ApacheWire.<init>(ApacheWire.java:109)
	at hr.com.vgv.verano.http.wire.apache.ApacheWire.<init>(ApacheWire.java:80)
	at hr.com.vgv.verano.http.response.Response.<init>(Response.java:81)
	at ru.fusionsoft.AppTest.httpPost(AppTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

Note: I have in my pom.xml
```
      <dependency>
          <groupId>org.cactoos</groupId>
          <artifactId>cactoos</artifactId>
          <version>0.50</version>
      </dependency>
```

You have in your pom.xml

```
        <dependency>
            <groupId>org.cactoos</groupId>
            <artifactId>cactoos</artifactId>
            <version>0.39</version>
        </dependency>
```

**Comment by Vatavuk** [comment]
@rocket-3 Thx for reporting, I've opened #60 to bump the version of cactoos.
